### ISSUE TITLE
"Earlier code should have sorted topologically or failed" assertion was hit

### ISSUE THREAD

**Issue by jnm2** [Techsola/tfvc-migrator#28]
Assertion was hit:

> System.InvalidOperationException: Should not be reachable. Earlier code should have sorted topologically or failed.

```
   at TfvcMigrator.Program.MigrateAsync(Uri projectCollectionUrl, String rootPath, String authors, String outDir, Nullable`1 minChangeset, Nullable`1 maxChangeset, ImmutableArray`1 rootPathChanges, String pat) in src\TfvcMigrator\Program.cs:line 278
   at TfvcMigrator.Program.MigrateAsync(Uri projectCollectionUrl, String rootPath, String authors, String outDir, Nullable`1 minChangeset, Nullable`1 maxChangeset, ImmutableArray`1 rootPathChanges, String pat) in src\TfvcMigrator\Program.cs:line 349
```

**Comment by jnm2** [comment]
I have a feeling that this might be something I also hit in a particular test migration scenario, prompting me to start on https://github.com/Techsola/tfvc-migrator/compare/main...support_branch_source_renames.

**Comment by JohanLarsson** [comment]
```
CS319321 (19,4 %, 1 331 ms/changeset, ETA 2,1 hours)...Unhandled exception: System.InvalidOperationException: A commit should have been created for the parent changeset 319103 before reaching this point.
```

**Comment by JohanLarsson** [comment]
Did more digging using the additional error info.
It goes wrong where we had a TFS branch that was merged more than once.

**Comment by jnm2** [comment]
I've seen it handle that scenario, I believe. There might be another element to it. Was the branch ever renamed? I have a branch in the works that starts reacting to source-renames.

**Comment by JohanLarsson** [comment]
I have no memory of the branch being renamed but have poor memory.

**Comment by JohanLarsson** [comment]
To expand on the above we have
1. A branch with two commits that were merged
2. Then more commits were added to the branch and it was merged again a couple of times.
3. Don't remember if there were any commits made the main branch between.
